export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('pets').del()

  // Inserts seed entries
  await knex('pets').insert([
    {
      id: 1,
      owner_id: 2,
      species: 'Dog',
      breed: 'Heading Dog',
      name: "Malu'i",
      sex: 'Male',
      desexed: true,
      colour: 'Black and White',
      age: 3,
      size: 'Medium',
      microchipped: true,
      home_suburb: 'Island Bay',
      last_location: 'Rangitoto Island, Auckland 1010, New Zealand',
      last_seen_date: '2025-10-09',
      photo_url: '/images/malu-i.jpg',
      lost: true,
      registration_number: 12345,
      latitude: '-36.7852905',
      longitude: '174.8636138',
    },
    {
      id: 2,
      owner_id: 3,
      species: 'Cat',
      breed: 'Russian Blue',
      name: 'Mochi',
      sex: 'Male',
      desexed: true,
      colour: 'Grey',
      age: 3,
      size: 'Medium',
      microchipped: true,
      home_suburb: 'Kingsland, Auckland, New Zealand',
      last_location: 'Home I Hope',
      last_seen_date: '2025-11-09',
      photo_url: '/images/mochi.jpg',
      lost: true,
      registration_number: 54321,
      latitude: '-36.8715458',
      longitude: '174.7470888',
    },
    {
      id: 3,
      owner_id: 4,
      species: 'Dog',
      breed: 'Dachshund',
      name: 'Feijoa',
      sex: 'Female',
      desexed: true,
      home_suburb: 'Milford',
      last_location: 'Milford Beach, Auckland 0620, New Zealand',
      last_seen_date: '2025-08-15',
      photo_url: '/images/dachshund.jpg',
      lost: true,
      registration_number: 98765,
      latitude: '-36.7673029',
      longitude: '174.7689278',
    },
    {
      id: 4,
      owner_id: 1,
      species: 'Dog',
      breed: 'Maltese',
      name: 'Charlie',
      sex: 'Male',
      desexed: true,
      home_suburb: 'Milford',
      last_location: 'Devonport, Auckland 0624, New Zealand',
      last_seen_date: '2025-01-09',
      photo_url: '/images/charlie.jpeg',
      lost: false,
      registration_number: 45612,
      latitude: '-36.8246787',
      longitude: '174.7985219',
    },
    {
      id: 5,
      owner_id: 1,
      species: 'Dog',
      breed: 'Jindo',
      name: 'Kiwi',
      sex: 'Female',
      desexed: true,
      home_suburb: 'Auckland Central',
      last_location: 'Auckland Central, Auckland 1010, New Zealand',
      last_seen_date: '2025-01-09',
      photo_url: '/images/kiwi.jpeg',
      lost: false,
      registration_number: 88618,
      latitude: '-36.8578672',
      longitude: '174.7572472',
    },
    {
      id: 6,
      owner_id: 1,
      species: 'Cat',
      breed: 'Russian Blue',
      name: 'Smokey',
      sex: 'Male',
      desexed: true,
      home_suburb: 'Auckland',
      last_location: 'Remuera, Auckland 1541, New Zealand',
      last_seen_date: '2025-01-09',
      photo_url: '/images/grey-cat.jpg',
      lost: true,
      registration_number: 75812,
      latitude: '-36.8807371',
      longitude: '174.7981276',
    },
  ])
}
