export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('pets').del()

  // Inserts seed entries
  await knex('pets').insert([
    {
      id: 1,
      owner_id: 2,
      species: 'dog',
      breed: 'heading dog',
      name: "malu'i",
      sex: 'male',
      desexed: 'true',
      colour: 'black and white',
      age: 3,
      size: 'medium',
      microchipped: 'true',
      home_suburb: 'island bay',
      last_location: 'island bay beach',
      last_seen_date: '2025-10-09',
      photo_url: '1000012489.jpg',
      lost: 'true',
      registration_number: 12345,
      latitude: '-36.848461',
      longitude: '174.763336',
    },
    {
      id: 2,
      owner_id: 3,
      species: 'cat',
      breed: 'russian blue',
      name: 'mochi',
      sex: 'male',
      desexed: 'true',
      colour: 'gray',
      age: 3,
      size: 'medium',
      microchipped: 'true',
      home_suburb: 'kingsland',
      last_location: 'home I hope',
      last_seen_date: '2025-11-09',
      photo_url: 'mochicat.jpg',
      lost: 'true',
      registration_number: 54321,
      latitude: '-20.84845',
      longitude: '175.763036',
    },
    {
      id: 3,
      owner_id: 4,
      species: 'dog',
      breed: 'dachshund',
      name: 'feijoa',
      sex: 'female',
      desexed: 'true',
      home_suburb: 'milford',
      last_location: 'milford beach',
      last_seen_date: '2025-08-15',
      photo_url: 'photoofadog.jpg',
      lost: 'true',
      registration_number: 98765,
      latitude: '-32.84845',
      longitude: '173.763036',
    },
    {
      id: 4,
      owner_id: 1,
      species: 'dog',
      breed: 'maltese',
      name: 'charlie',
      sex: 'female',
      desexed: 'true',
      home_suburb: 'milford',
      last_location: 'milford beach',
      last_seen_date: '2025-01-09',
      photo_url: 'charlie.jpg',
      lost: 'false',
      registration_number: 45612,
      latitude: '-36.84845',
      longitude: '174.763036',
    },
  ])
}
